set SynModuleInfo {
  {SRCNAME RNI_Pipeline_VITIS_LOOP_33_2 MODELNAME RNI_Pipeline_VITIS_LOOP_33_2 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_33_2
    SUBMODULES {
      {MODELNAME RNI_flow_control_loop_pipe_sequential_init RTLNAME RNI_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME RNI_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME RNI_Pipeline_VITIS_LOOP_42_3 MODELNAME RNI_Pipeline_VITIS_LOOP_42_3 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_42_3}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP MODELNAME RNI_Pipeline_WEIGHTS_LOOP RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP}
  {SRCNAME inner_layer_Pipeline_WEIGHTS_LOOP MODELNAME inner_layer_Pipeline_WEIGHTS_LOOP RTLNAME RNI_inner_layer_Pipeline_WEIGHTS_LOOP
    SUBMODULES {
      {MODELNAME RNI_inner_layer_Pipeline_WEIGHTS_LOOP_WEIGHTS_ROM_AUTO_1R RTLNAME RNI_inner_layer_Pipeline_WEIGHTS_LOOP_WEIGHTS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME inner_layer_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME inner_layer_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_inner_layer_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME inner_layer MODELNAME inner_layer RTLNAME RNI_inner_layer
    SUBMODULES {
      {MODELNAME RNI_inner_layer_NEURONS_INDEX_ROM_AUTO_1R RTLNAME RNI_inner_layer_NEURONS_INDEX_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_inner_layer_WEIGHTS_INDEX_ROM_AUTO_1R RTLNAME RNI_inner_layer_WEIGHTS_INDEX_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP1 MODELNAME RNI_Pipeline_WEIGHTS_LOOP1 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP1}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME RNI_Pipeline_VITIS_LOOP_66_5 MODELNAME RNI_Pipeline_VITIS_LOOP_66_5 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_66_5}
  {SRCNAME RNI MODELNAME RNI RTLNAME RNI IS_TOP 1
    SUBMODULES {
      {MODELNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_input_list_RAM_AUTO_1R1W RTLNAME RNI_input_list_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_regslice_both RTLNAME RNI_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME RNI_regslice_both_U}
    }
  }
}
