set SynModuleInfo {
  {SRCNAME RNI_Pipeline_VITIS_LOOP_33_2 MODELNAME RNI_Pipeline_VITIS_LOOP_33_2 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_33_2
    SUBMODULES {
      {MODELNAME RNI_flow_control_loop_pipe_sequential_init RTLNAME RNI_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME RNI_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME RNI_Pipeline_VITIS_LOOP_39_3 MODELNAME RNI_Pipeline_VITIS_LOOP_39_3 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_39_3}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP MODELNAME RNI_Pipeline_WEIGHTS_LOOP RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP1 MODELNAME RNI_Pipeline_WEIGHTS_LOOP1 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP1}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP2 MODELNAME RNI_Pipeline_WEIGHTS_LOOP2 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP2}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP3 MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP3 RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP3}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP4 MODELNAME RNI_Pipeline_WEIGHTS_LOOP4 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP4}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP5 MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP5 RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP5}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP6 MODELNAME RNI_Pipeline_WEIGHTS_LOOP6 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP6}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP7 MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP7 RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP7}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP8 MODELNAME RNI_Pipeline_WEIGHTS_LOOP8 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP8}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP9 MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP9 RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP9}
  {SRCNAME RNI_Pipeline_VITIS_LOOP_55_4 MODELNAME RNI_Pipeline_VITIS_LOOP_55_4 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_55_4}
  {SRCNAME RNI MODELNAME RNI RTLNAME RNI IS_TOP 1
    SUBMODULES {
      {MODELNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_WEIGHTS_INDEX_ROM_AUTO_1R RTLNAME RNI_WEIGHTS_INDEX_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_WEIGHTS_ROM_AUTO_1R RTLNAME RNI_WEIGHTS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_input_list_RAM_AUTO_1R1W RTLNAME RNI_input_list_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_regslice_both RTLNAME RNI_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME RNI_regslice_both_U}
    }
  }
}
