set SynModuleInfo {
  {SRCNAME RNI_Pipeline_VITIS_LOOP_54_1 MODELNAME RNI_Pipeline_VITIS_LOOP_54_1 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_54_1
    SUBMODULES {
      {MODELNAME RNI_flow_control_loop_pipe_sequential_init RTLNAME RNI_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME RNI_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME input_layer_Pipeline_WEIGHTS_LOOP_0 MODELNAME input_layer_Pipeline_WEIGHTS_LOOP_0 RTLNAME RNI_input_layer_Pipeline_WEIGHTS_LOOP_0
    SUBMODULES {
      {MODELNAME RNI_mul_32s_8s_40_2_1 RTLNAME RNI_mul_32s_8s_40_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME RNI_mux_4_2_32_1_1 RTLNAME RNI_mux_4_2_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME RNI_input_layer_Pipeline_WEIGHTS_LOOP_0_WEIGHTS_ROM_AUTO_1R RTLNAME RNI_input_layer_Pipeline_WEIGHTS_LOOP_0_WEIGHTS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME input_layer MODELNAME input_layer RTLNAME RNI_input_layer
    SUBMODULES {
      {MODELNAME RNI_mul_16s_17ns_33_1_1 RTLNAME RNI_mul_16s_17ns_33_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME RNI_input_layer_BIASES_ROM_AUTO_1R RTLNAME RNI_input_layer_BIASES_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_input_layer_WEIGHTS_INDEX_ROM_AUTO_1R RTLNAME RNI_input_layer_WEIGHTS_INDEX_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME inner_layer_1_Pipeline_WEIGHTS_LOOP_1 MODELNAME inner_layer_1_Pipeline_WEIGHTS_LOOP_1 RTLNAME RNI_inner_layer_1_Pipeline_WEIGHTS_LOOP_1}
  {SRCNAME inner_layer_1_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME inner_layer_1_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_inner_layer_1_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME inner_layer_1 MODELNAME inner_layer_1 RTLNAME RNI_inner_layer_1}
  {SRCNAME inner_layer_2_Pipeline_WEIGHTS_LOOP_2 MODELNAME inner_layer_2_Pipeline_WEIGHTS_LOOP_2 RTLNAME RNI_inner_layer_2_Pipeline_WEIGHTS_LOOP_2}
  {SRCNAME inner_layer_2_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME inner_layer_2_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_inner_layer_2_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME inner_layer_2 MODELNAME inner_layer_2 RTLNAME RNI_inner_layer_2}
  {SRCNAME inner_layer_3_Pipeline_WEIGHTS_LOOP_3 MODELNAME inner_layer_3_Pipeline_WEIGHTS_LOOP_3 RTLNAME RNI_inner_layer_3_Pipeline_WEIGHTS_LOOP_3}
  {SRCNAME inner_layer_3_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME inner_layer_3_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_inner_layer_3_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME inner_layer_3 MODELNAME inner_layer_3 RTLNAME RNI_inner_layer_3}
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP_4 MODELNAME RNI_Pipeline_WEIGHTS_LOOP_4 RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP_4}
  {SRCNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP MODELNAME RNI_Pipeline_NEURONS_STATE_RESET_LOOP RTLNAME RNI_RNI_Pipeline_NEURONS_STATE_RESET_LOOP}
  {SRCNAME RNI_Pipeline_VITIS_LOOP_197_1 MODELNAME RNI_Pipeline_VITIS_LOOP_197_1 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_197_1}
  {SRCNAME RNI MODELNAME RNI RTLNAME RNI IS_TOP 1
    SUBMODULES {
      {MODELNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_out_pkts_keep_RAM_AUTO_1R1W RTLNAME RNI_out_pkts_keep_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_out_pkts_user_RAM_AUTO_1R1W RTLNAME RNI_out_pkts_user_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_out_pkts_last_RAM_AUTO_1R1W RTLNAME RNI_out_pkts_last_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_out_pkts_id_RAM_AUTO_1R1W RTLNAME RNI_out_pkts_id_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_out_pkts_dest_RAM_AUTO_1R1W RTLNAME RNI_out_pkts_dest_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_ctrl_s_axi RTLNAME RNI_ctrl_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME RNI_regslice_both RTLNAME RNI_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME RNI_regslice_both_U}
    }
  }
}
