set SynModuleInfo {
  {SRCNAME RNI_Pipeline_VITIS_LOOP_29_2 MODELNAME RNI_Pipeline_VITIS_LOOP_29_2 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_29_2
    SUBMODULES {
      {MODELNAME RNI_flow_control_loop_pipe_sequential_init RTLNAME RNI_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME RNI_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP MODELNAME RNI_Pipeline_WEIGHTS_LOOP RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP
    SUBMODULES {
      {MODELNAME RNI_mux_4_2_8_1_1 RTLNAME RNI_mux_4_2_8_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME RNI_mac_muladd_8s_8s_8ns_8_4_1 RTLNAME RNI_mac_muladd_8s_8s_8ns_8_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME RNI_RNI_Pipeline_WEIGHTS_LOOP_WEIGHTS_ROM_AUTO_1R RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP_WEIGHTS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME RNI_Pipeline_NEURONS_LOOP MODELNAME RNI_Pipeline_NEURONS_LOOP RTLNAME RNI_RNI_Pipeline_NEURONS_LOOP}
  {SRCNAME RNI_Pipeline_NEURONS_LOOP1 MODELNAME RNI_Pipeline_NEURONS_LOOP1 RTLNAME RNI_RNI_Pipeline_NEURONS_LOOP1}
  {SRCNAME RNI MODELNAME RNI RTLNAME RNI IS_TOP 1
    SUBMODULES {
      {MODELNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_MEMBRANE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_NEURONS_INDEX_ROM_AUTO_1R RTLNAME RNI_NEURONS_INDEX_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_WEIGHTS_INDEX_ROM_AUTO_1R RTLNAME RNI_WEIGHTS_INDEX_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_control_s_axi RTLNAME RNI_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME RNI_regslice_both RTLNAME RNI_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME RNI_regslice_both_U}
    }
  }
}
