

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.NEURONS_MEMBRANE_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.NEURONS_STATE_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.WEIGHTS_INDEX_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.WEIGHTS_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_RNI_Pipeline_VITIS_LOOP_29_2_fu_267"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_RNI_Pipeline_VITIS_LOOP_29_2_fu_267.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_RNI_Pipeline_INPUT_LAYER_NEURONS_LOOP_fu_280"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_RNI_Pipeline_INPUT_LAYER_NEURONS_LOOP_fu_280.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.NEURONS_INDEX_U"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.WEIGHTS_INDEX_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.grp_inner_layer_Pipeline_INNER_LAYER_WEIGHTS_LOOP_fu_137"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.grp_inner_layer_Pipeline_INNER_LAYER_WEIGHTS_LOOP_fu_137.WEIGHTS_U"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.grp_inner_layer_Pipeline_INNER_LAYER_WEIGHTS_LOOP_fu_137.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.grp_inner_layer_Pipeline_NEURONS_STATE_RESET_LOOP_fu_150"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_inner_layer_fu_292.grp_inner_layer_Pipeline_NEURONS_STATE_RESET_LOOP_fu_150.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_RNI_Pipeline_OUTPUT_LAYER_WEIGHTS_LOOP_fu_309"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_RNI_Pipeline_OUTPUT_LAYER_WEIGHTS_LOOP_fu_309.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_data_V_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_keep_V_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_strb_V_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_user_V_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_last_V_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_id_V_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_dest_V_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_data_V_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_keep_V_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_strb_V_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_user_V_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_last_V_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_id_V_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_dest_V_U"}]}
set DependenceCheckSize 0
