set SynModuleInfo {
  {SRCNAME LIGHT_MODULE_Pipeline_VITIS_LOOP_16_2 MODELNAME LIGHT_MODULE_Pipeline_VITIS_LOOP_16_2 RTLNAME LIGHT_MODULE_LIGHT_MODULE_Pipeline_VITIS_LOOP_16_2
    SUBMODULES {
      {MODELNAME LIGHT_MODULE_flow_control_loop_pipe_sequential_init RTLNAME LIGHT_MODULE_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME LIGHT_MODULE_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME LIGHT_MODULE_Pipeline_VITIS_LOOP_42_1 MODELNAME LIGHT_MODULE_Pipeline_VITIS_LOOP_42_1 RTLNAME LIGHT_MODULE_LIGHT_MODULE_Pipeline_VITIS_LOOP_42_1
    SUBMODULES {
      {MODELNAME LIGHT_MODULE_mux_4_2_32_1_1 RTLNAME LIGHT_MODULE_mux_4_2_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME LIGHT_MODULE_Pipeline_VITIS_LOOP_22_3 MODELNAME LIGHT_MODULE_Pipeline_VITIS_LOOP_22_3 RTLNAME LIGHT_MODULE_LIGHT_MODULE_Pipeline_VITIS_LOOP_22_3}
  {SRCNAME LIGHT_MODULE MODELNAME LIGHT_MODULE RTLNAME LIGHT_MODULE IS_TOP 1
    SUBMODULES {
      {MODELNAME LIGHT_MODULE_ctrl_s_axi RTLNAME LIGHT_MODULE_ctrl_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME LIGHT_MODULE_regslice_both RTLNAME LIGHT_MODULE_regslice_both BINDTYPE interface TYPE interface_regslice INSTNAME LIGHT_MODULE_regslice_both_U}
    }
  }
}
