set SynModuleInfo {
  {SRCNAME RNI_Pipeline_WEIGHTS_LOOP MODELNAME RNI_Pipeline_WEIGHTS_LOOP RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP
    SUBMODULES {
      {MODELNAME RNI_mul_8s_32s_32_2_1 RTLNAME RNI_mul_8s_32s_32_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME RNI_RNI_Pipeline_WEIGHTS_LOOP_WEIGHTS_ROM_AUTO_1R RTLNAME RNI_RNI_Pipeline_WEIGHTS_LOOP_WEIGHTS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_flow_control_loop_pipe_sequential_init RTLNAME RNI_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME RNI_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME RNI_Pipeline_VITIS_LOOP_76_1 MODELNAME RNI_Pipeline_VITIS_LOOP_76_1 RTLNAME RNI_RNI_Pipeline_VITIS_LOOP_76_1}
  {SRCNAME RNI MODELNAME RNI RTLNAME RNI IS_TOP 1
    SUBMODULES {
      {MODELNAME RNI_NEURONS_ROM_AUTO_1R RTLNAME RNI_NEURONS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_NEURONS_MEM_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_MEM_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W RTLNAME RNI_NEURONS_STATE_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME RNI_gmem_m_axi RTLNAME RNI_gmem_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME RNI_control_s_axi RTLNAME RNI_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
