# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mohr0901/Documents/PMC/H_ARDUINO_RNI/Pynq_Z2/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_auto_pc_7/base_auto_pc_7.xci
# IP: The module: 'base_auto_pc_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mohr0901/Documents/PMC/H_ARDUINO_RNI/Pynq_Z2/base/myproj/project_1.gen/sources_1/bd/base/ip/base_auto_pc_7/base_auto_pc_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mohr0901/Documents/PMC/H_ARDUINO_RNI/Pynq_Z2/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_auto_pc_7/base_auto_pc_7.xci
# IP: The module: 'base_auto_pc_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mohr0901/Documents/PMC/H_ARDUINO_RNI/Pynq_Z2/base/myproj/project_1.gen/sources_1/bd/base/ip/base_auto_pc_7/base_auto_pc_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
